In [1]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_excel('Apriori.xlsx', index_col=0)

In [6]:
df

    1  2  3  4  5
T1  1  1  0  0  1
T2  0  1  0  1  0
T3  0  1  1  0  0
T4  1  1  0  1  0
T5  1  0  1  0  0
T6  0  1  1  0  0
T7  1  0  1  0  0
T8  1  1  1  0  1
T9  1  1  1  0  0

In [9]:
pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.18.0-py2.py3-none-any.whl (1.3 MB)
Requirement already satisfied: setuptools in c:\users\samsung\anaconda3\lib\site-packages (from mlxtend) (45.2.0.post20200210)
Requirement already satisfied: joblib>=0.13.2 in c:\users\samsung\anaconda3\lib\site-packages (from mlxtend) (0.14.1)
Requirement already satisfied: scikit-learn>=0.20.3 in c:\users\samsung\anaconda3\lib\site-packages (from mlxtend) (0.24.2)
Requirement already satisfied: pandas>=0.24.2 in c:\users\samsung\anaconda3\lib\site-packages (from mlxtend) (1.1.1)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\samsung\anaconda3\lib\site-packages (from mlxtend) (3.3.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\samsung\anaconda3\lib\site-packages (from mlxtend) (1.18.1)
Requirement already satisfied: scipy>=1.2.1 in c:\users\samsung\anaconda3\lib\site-packages (from mlxtend) (1.4.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\samsung\anaconda3\lib\site-packages (from scikit-learn>=0.20.3->mlxtend) (2.1.0)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\samsung\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in c:\users\samsung\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2019.3)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\samsung\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.4.6)
Requirement already satisfied: pillow>=6.2.0 in c:\users\samsung\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (7.0.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\samsung\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.1.0)
Requirement already satisfied: certifi>=2020.06.20 in c:\users\samsung\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2020.6.20)
Requirement already satisfied: cycler>=0.10 in c:\users\samsung\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.10.0)
Requirement already satisfied: six>=1.5 in c:\users\samsung\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.24.2->mlxtend) (1.14.0)
Installing collected packages: mlxtend
Successfully installed mlxtend-0.18.0
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 20.2.3; however, version 21.2.4 is available.
You should consider upgrading via the 'C:\Users\Samsung\anaconda3\python.exe -m pip install --upgrade pip' command.

In [10]:
from mlxtend.frequent_patterns import apriori, association_rules

In [12]:
frequent_itemsets = apriori(df, min_support =0.087, use_colnames = True)
#foi definido 0.087 porque no enunciado do problema deu o SupMin = 2 e s√£o 23 itens comprados min_suport=2/23=0.087.

In [13]:
frequent_itemsets

     support      itemsets
0   0.666667           (1)
1   0.777778           (2)
2   0.666667           (3)
3   0.222222           (4)
4   0.222222           (5)
5   0.444444        (1, 2)
6   0.444444        (1, 3)
7   0.111111        (1, 4)
8   0.222222        (1, 5)
9   0.444444        (2, 3)
10  0.222222        (2, 4)
11  0.222222        (2, 5)
12  0.111111        (3, 5)
13  0.222222     (1, 2, 3)
14  0.111111     (1, 2, 4)
15  0.222222     (1, 2, 5)
16  0.111111     (1, 3, 5)
17  0.111111     (2, 3, 5)
18  0.111111  (1, 2, 3, 5)